# _   _               _          _   _ ____  _          _ _
#| \ | | ___ _   _   / \   _ __ | |_(_) ___|| | ___   _| | |
#|  \| |/ _ \ | | | / _ \ | '_ \| __| \___ \| |/ / | | | | |
#| |\  |  __/ |_| |/ ___ \| | | | |_| |___) |   <| |_| | | |
#|_| \_|\___|\__, /_/   \_\_| |_|\__|_|____/|_|\_\\__,_|_|_|
#            |___/

# Developer - https://t.me/NeyOff
# Especially for spigotmc.ru

settings:
  enabled: true # Block head placement
  permissions:
    enabled: false # Enable permission system (bypass.place, bypass.takeaway)
  take_away:
    enabled: true # Take away the head(s) the player attempted to place, if blocking is active
    type: HAND # HAND — remove only the head from the hand used to place it.
    # ALL — remove all heads from the player's inventory.

  list: # List of head names that are not allowed to be placed (HEX colors supported)
    enabled: true # If false - all heads will be blocked (regardless of name)
    names:
      - "&aPlayer Head"
      - "Player Head"
      - "#42fffcPlayer Head"

messages:
  on_place:
    enabled: true
    text:
      - ""
      - " #efff5e[⚠] #ecff45Attention! Placement of this item is prohibited. "
      - ""