# _   _               _          _   _ ____  _          _ _
#| \ | | ___ _   _   / \   _ __ | |_(_) ___|| | ___   _| | |
#|  \| |/ _ \ | | | / _ \ | '_ \| __| \___ \| |/ / | | | | |
#| |\  |  __/ |_| |/ ___ \| | | | |_| |___) |   <| |_| | | |
#|_| \_|\___|\__, /_/   \_\_| |_|\__|_|____/|_|\_\\__,_|_|_|
#            |___/

# Разработчик - https://t.me/NeyOff
# Специально для spigotmc.ru

settings:

  enabled: true #Блокировать установку головы
  take_away:
    enabled: false #Отбирать голов(ы), которую игрок пытался поставить, если блокировка активирована
    type: HAND # HAND — удалять только голову из той руки, которой игрок пытался поставить голову.
               # ALL — удалять все головы из инвентаря игрока.

  list: #Список названий голов, установка которых не разрешена (Поддерживается HEX)
    enabled: true #Если false - будут блокироваться все головы (в независимости от названия)
    names:
      - "&aГолова игрока"
      - "Голова игрока"
      - "#42fffcГолова игрока"

messages:
  on_place:
    enabled: true
    text:
      - ""
      - " #efff5e[⚠] #ecff45Внимание! Установка данного игрового предмета запрещена. "
      - ""